name: Build and Publish Docs

on:
  push:
    branches:    
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Docs
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs"
          pre-build-command: "apt-get install -y graphviz libgraphviz-dev && python -m pip install --upgrade pip && pip install sphinx && pip install setuptools wheel && cd db_update && python setup.py install && cd ../control_plane/protos && python setup.py install && cd ../../control_plane/controller && python setup.py install && cd ../../ && cd ../../control_plane/node-manager && python setup.py install"

      - name: Commit documentation changes
        run: |
          git clone https://github.com/netgroup/rose-srv6-control-plane.git --branch gh-pages --single-branch gh-pages
          mkdir -p gh-pages/latest
          cp -r docs/build/html/* gh-pages/latest
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update documentation" -a || true
          # The above command will fail if no changes were present, so we ignore
          # that.

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
      # ===============================
