name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code
      
      - name: Build Docker Controller image
        if: ${{ github.event_name == 'pull_request'}}
        uses: zvfvrv/docker-bpgpr@v1.0.1
        with:
          gh_token: ${{ secrets.TOKEN_GITHUB }}
          image_name: rose-srv6-controller
          target: controller
          push: false

      - name: Build Docker Node-manager image
        if: ${{ github.event_name == 'pull_request'}}
        uses: zvfvrv/docker-bpgpr@v1.0.1
        with:
          gh_token: ${{ secrets.TOKEN_GITHUB }}
          image_name: rose-srv6-node-manager
          target: node-manager
          push: false

      - name: Build and Publish Docker Controller image GPR
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master'}}
        uses: zvfvrv/docker-bpgpr@v1.0.1
        with:
          gh_token: ${{ secrets.TOKEN_GITHUB }}
          image_name: rose-srv6-controller
          tags: latest
          tag_with_ref: true
          tag_with_sha: true
          target: controller
          push: true

      - name: Build and Publish Docker Node-manager image GPR
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master'}}
        uses: zvfvrv/docker-bpgpr@v1.0.1
        with:
          gh_token: ${{ secrets.TOKEN_GITHUB }}
          image_name: rose-srv6-node-manager
          tags: latest
          tag_with_ref: true
          tag_with_sha: true
          target: node-manager
          push: true
      
      - name: Build and Publish Docker Controller image DockerHub
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master'}}
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: rosesrv6/rose-srv6-node-manager
          target: node-manager
          tag_with_ref: true
          tags: latest
      
      - name: Build and Publish Docker Node-manager image DockerHub
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master'}}
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: rosesrv6/rose-srv6-controller
          target: controller
          tag_with_ref: true
          tags: latest
